### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by Krakama** [Owlet7/wadfusion#11]
![image](https://github.com/user-attachments/assets/884002fd-e7a5-4a94-8e89-93a60b0bc13a)
Download link leads to a "Not Found" page

**Comment by domyoji81** [comment]
![Capture](https://github.com/user-attachments/assets/82432597-e240-4c45-96bc-478cb4c9a7d2)

Can grab it this way in the meantime.

**Comment by Owlet7** [comment]
Yeah, it's a placeholder for now, until we have the first release (soon).

**Comment by Krakama** [comment]
I tried that. It didn't seem to work. Couldn't figure out how to make the
Doom_Complete.pk3 without the exe

**Comment by domyoji81** [comment]
If it's not running then you're likely missing python. Download and install that, then try running wadfusion.py again.

**Comment by Owlet7** [comment]
Now that we have a release, the link works.
