### ISSUE TITLE
Handler looks for old CVar `wf_ml_texswap`

### ISSUE THREAD

**Issue by TwelveEyes** [Owlet7/wadfusion#12]
https://github.com/Owlet7/wadfusion/blob/1e9571f09aeea20d9b33f5d2ff349ce461d8a0c4/res/zscript/wf_handler.zs#L218

`wf_ml_texswap` was renamed to `wf_masterlevels_texswap`. This will cause a VM abort on fresh config files.

**Comment by Owlet7** [comment]
Oops, forgot that I already added that to the handler. Corrected it, and commented it out for now, since it's not actually used yet.
