### ISSUE TITLE
Feature Request - Update Episode Menu To Doom Font

### ISSUE THREAD

**Issue by Zoltar007** [Owlet7/wadfusion#17]
Currently the episode list is displayed in a generic font:
![Screenshot 2024-10-11 175859](https://github.com/user-attachments/assets/cc993196-d151-422a-88cb-57c52af46bf3)

As per [WadSmoosh](https://heptapod.host/jp-lebreton/wadsmoosh) (which WadFusion is based on) the episode list was displayed in the Doom font:
![Screenshot 2024-10-11 174809](https://github.com/user-attachments/assets/769c3f7c-d110-427b-a051-4c366348ee2d)

This was accomplished in WadSmoosh, which added the following lines to the top of [menudef.txt](https://heptapod.host/jp-lebreton/wadsmoosh/-/blob/branch/default/res/menudef.txt?ref_type=heads):
```
ListMenu "EpisodeMenu"
{
    Font "BigFont", "RED"
    Linespacing 18
    
    StaticPatch 50, 2, "M_EPISOD"
    Position 30, 30
    
    ForceList
}

```

Modifying `res/menudef.txt` in this repository has the intended result:
![Screenshot 2024-10-11 175628](https://github.com/user-attachments/assets/c48ed564-45b8-49a5-a9a5-c3befc74a5df)

Would it be possible to implement this (as at least optional) in a future release of WadFusion?

**Comment by Owlet7** [comment]
The issue with this method is that the menu gets cut off when it's properly scaled and aspect ratio corrected:
![image](https://github.com/user-attachments/assets/68e8ed4f-64e3-4fd1-989d-738df659334d)

It was also an issue in WadSmoosh, JP just expected people to turn proper scaling off.

This will be corrected differently, see #6.
