### ISSUE TITLE
Bad syntax with animated fire sky

### ISSUE THREAD

**Issue by Shockwave508** [Owlet7/wadfusion#18]
GZDoom finally updated to v4.13.0, but I still can't play WADFusion due to bad syntax with what I can only assume is the animated sky for Legacy of Rust. 

Affected File: animdefs.txt, lines 358 and 952, "firetexture SKYX4A tics 2.00025"

OS: SteamOS v3.6.18 Beta
GZDoom version: Flatpak 4.13.0

**Comment by Zoltar007** [comment]
I can't replicate this at all on the Windows 64bit version of 4.13.0. However, I can replicate it on 4.12.2.
Have you confirmed that your current installed version of GZDoom reports as "g4.13.0" in the console?

**Comment by Owlet7** [comment]
We confirmed that the issue is that the flathub package hasn't updated yet.
