### ISSUE TITLE
script does not complete

### ISSUE THREAD

**Issue by JimFlasch** [Owlet7/wadfusion#23]
I have tried this script in both the current version and the immediate previous version (tried in separate clean installs) and both fail to complete as they should. I  did not get a doom_fusion.ipk3 file (or doom_complete.pk3 file with the previous version), only a temp folder with seven folders of extracted data and two empty folders, mapinfo and zscript. The last line in the log file (attached to this post) is " Extracting source_wads/CABALL.WAD map MAP30 to temp/maps/ML_MAP43.wad" I use Windows 10, BTW.

[wadfusion.log](https://github.com/user-attachments/files/17446776/wadfusion.log)

**Comment by domyoji81** [comment]
This is just a shot in the dark, but you could try removing the Master Levels Rejects wads and see if the script completes without them. If it does, try deleting your **CABALL.wad** and **MINES.wad** and redownload them from the links Owlet7 posted (for the off chance that something was wrong with the original ones you downloaded), then put all the Rejects wads back in source_wads and run the script again.

I was able to replicate your log by intentionally "corrupting" MINES.wad (via cutting TRW out). Maybe you'll get lucky and it'll turn out to just have been a corrupt download.

**Comment by JimFlasch** [comment]
redownloading all the Master Level Rejects did it - thanks.
