### ISSUE TITLE
[Master Levels] Use only the progression from "Works of the Masters"

### ISSUE THREAD

**Issue by elf-alchemist** [Owlet7/wadfusion#24]
With the addition of the rejected Master Levels, it feels a missed opportunity to not use the progression established in WotM for the ML by default. This would significantly, simplify the experience of user choice and promote a better quality experience out-of-the-box. As the rejects can simply be bundled with WadFusion, just as how they were in WotM.

https://doomwiki.org/wiki/Works_of_the_Masters

**Comment by Owlet7** [comment]
I'm confused, what exactly are you suggesting to be changed?

**Comment by elf-alchemist** [comment]
> I'm confused, what exactly are you suggesting to be changed?

To have the level progression and episode structure of WotM be the default, and possibly only choice, to make the requirement of all the rejected levels a base need to include the ML.
 
> I won't change the order of the Cabal episode, since the order in WotM isn't consistent with what's said in the maps' readme files.

The progression that JPL came up with for WotM was spawned out of a [direct email exchange with Sverre himself](https://doomwiki.org/wiki/Works_of_the_Masters#cite_note-1). In spite of the earlier's text files, the author's own later words rectify the order to a much more engaging sequence of maps. Unless you are interested in remaking 20 missing maps from the original 32-map megawad plan, this is the better bet for the 12-map Cabal's level progression.

> I prefer not to change the order of Christen Klie's maps, because WotM ignores Xaser's order, which is now official.

Having something be "official" isn't really substantive with the ML, as anything short of structuring each series that were featured on the Master Levels project as it's own episode will bring down the quality of the ML experience as a whole, no 21 map megawad compilation of the ML is a worth-while experience in comparison to having, let's say Inferno as a single episode, distinct from Titan as it's own episode, distinct from Cabal as it's own episode, etc.

> The WADs won't be bundled with WadFusion either, all WADs are BYO, and which to bring is user choice.

I mean that is understandable, but everything is about balance. I'm just making the argument that this moment is the one time where the choice most people will make is subpar at best, and a depressing disregard of the involved authors' works by simply underselling the maps they made on a package that lacks any type of cohesion or consistency, of which WotM is the only one to truly achieve.

**Comment by Owlet7** [comment]
>To have the level progression and episode structure of WotM be the default, and possibly only choice, to make the requirement of all the rejected levels a base need to include the ML.

Absolutely no.

>The progression that JPL came up with for WotM was spawned out of a direct email exchange with Sverre himself.

I am not privy to that exchange, so I am unable to make any decisions based on it. The readme files are all that I have to go on, and frankly that is the order that I prefer, and is the only order which will make sense once the story intermission screens are added.

Including support for the rejects already stretches the intended purpose of the project, which is to include all official releases. Works of the Masters is not an official release by any means, and I didn't take it into account when adding support for the rejects (I only took the music selection for Klie's rejects levels from it).
