### ISSUE TITLE
[REQUEST] Additional WAD support from WADSMOOSH-PLUS

### ISSUE THREAD

**Issue by staticnation** [Owlet7/wadfusion#25]
there is another Fork ([WADSMOOSH-PLUS](https://github.com/vanessakindell/wadsmoosh-plus)) that supports some additional WADs

This is a request to bring those supported WADs into Wadfusion

**Comment by Owlet7** [comment]
Please read the [readme](https://github.com/Owlet7/wadfusion/blob/master/README.md):

>WadFusion is not a general-purpose tool for merging DOOM WADs; it is for *merging official content* only — it was created out of a desire for a "complete" version of retail DOOM and DOOM II. Please do not ask if WadFusion will support any specific WAD. If you want to add your own content to a custom IWAD, please either modify [WadFusion's source code](https://github.com/Owlet7/wadfusion) yourself, or simply edit the `doom_fusion.ipk3` file that WadFusion generated. Please do not ask us for support when doing either, try consulting the [ZDoom Wiki](https://zdoom.org/wiki/Main_Page) instead.

WadSmoosh Plus does not support any official WADs that aren't also supported by WadFusion.
