### ISSUE TITLE
Jaguar/Playstation 1 maps

### ISSUE THREAD

**Issue by Someguyman** [Owlet7/wadfusion#26]
Will support ever be added to the console maps from the jaguar/playstation version? Considering the levels are already on the idgames archive. 

https://www.doomworld.com/idgames/levels/doom2/Ports/p-r/psxhellgate
https://www.doomworld.com/idgames/levels/doom2/Ports/p-r/psxhellkeep
https://www.doomworld.com/idgames/levels/doom2/Ports/p-r/psxtwilight
https://www.doomworld.com/idgames/levels/doom2/Ports/p-r/psxthreshold
https://www.doomworld.com/idgames/levels/doom2/Ports/p-r/psxmarshes
https://www.doomworld.com/idgames/levels/doom2/Ports/p-r/psxmansion
https://www.doomworld.com/idgames/levels/doom2/Ports/p-r/psxclubdoom
https://www.doomworld.com/idgames/levels/doom2/Ports/p-r/psxredemption

**Comment by AlecsBrito** [comment]
Could use the consoledoom.wad, i think the maps are more faithful to console ones.

https://allfearthesentinel.com/zandronum/wads.php?name=consoledoom.wad&from=WadArchive

**Comment by Owlet7** [comment]
None of the 5th gen console Doom content will ever be officially supported in WadFusion, for several reasons:
- There's no practical way of extracting their content from a ROM dump (that will work with GZDoom)
- There are too many ports to consider
- None of the PC conversions are official
- That generation of DOOM ports is too different from the PC version
