### ISSUE TITLE
Script error, "doom_fusion.ipk3;cvarinfo.txt" line 1:

### ISSUE THREAD

**Issue by 0QwertyAsdf0** [Owlet7/wadfusion#27]
cvar 'wf_sigil_shreds' already exists

**Comment by Owlet7** [comment]
Could you please try resetting the settings by deleting all lines starting with "wf_" in your GZDoom .ini file?

**Comment by 0QwertyAsdf0** [comment]
i deleted the entire file and it didn't work

**Comment by Owlet7** [comment]
Which version of GZDoom are you using? Can you upload the wadfusion.log file that was generated?

**Comment by domyoji81** [comment]
GZDoom throwing that error means wf_sigil_shreds is being defined in multiple places. And seeing as how that variable is probably unique to fusion (via the "wf_" prefix), it's highly unlikely you would encounter that specific error unless you're somehow doubling up on it. Are you perhaps trying to drag and drop the doom_fusion.ipk3 onto gzdoom.exe, then selecting Doom Fusion in the menu? That would lead to doubling up and cause GZDoom to throw the error that you're getting. If not, are you maybe trying to run some custom build of it or pairing it with something else?

**Comment by 0QwertyAsdf0** [comment]
that was indeed the problem
