### ISSUE TITLE
Support for Ultraviolence +

### ISSUE THREAD

**Issue by aeronius** [Owlet7/wadfusion#35]
Possible to add UV+ as a selectable difficulty?  I know I can set it in the console with  sv_alwaysspawnmulti 1, but it'd be nice to have it as an option up front.

Great work on this by the way.  Really makes playing Doom a treat.

**Comment by Owlet7** [comment]
I prefer to avoid adding additional skill levels, especially for stuff that can be toggled in GZDoom's gameplay options menu.

![image](https://github.com/user-attachments/assets/6271817e-9124-4719-b414-bd9b916b0619)

Removing WadSmoosh's UV+ was one of the first things I did when JPL announced he would stop supporting it (meaning he wouldn't accept fixes from this fork). I never liked it, thought it was dumb for the Unity port to add it, and the presentation for it in WS was kinda jank. The KEX port that replaced the Unity port also removed it, instead adding gameplay options like in GZDoom.

If you really want it, you can restore it by adding this to WF's `mapinfo.txt`:
```
// define UV+ skill
skill hardplus
{
	SpawnFilter = Hard
	Name = "Ultra-Violence+"
	PicName = "M_ULTRAP"
	Key = "u"
	FastMonsters
	SpawnMulti
}
```
You can add this image to the `graphics` directory to make it fit better, make sure it's named `M_ULTRAP.png`:
![M_ULTRAP](https://github.com/user-attachments/assets/d969fbe3-2569-40b3-8530-603b586c07c9)

**Comment by aeronius** [comment]
This is excellent. understand your reasons for keeping it out; I actually find UV+ quite enjoyable.  Different strokes!  Thanks for the swift reply.
