### ISSUE TITLE
Implement 25th Anniversary Midi Tracks for Master Levels, No Rest for the Living, and Plutonia

### ISSUE THREAD

**Issue by mdlomn** [Owlet7/wadfusion#38]
Would it be possible to implement the 25th anniversary midi packs for these wads? It would be nice to have custom music for all the levels 

Master Levels: https://www.doomworld.com/forum/topic/118804-master-levels-for-doom-ii-25th-anniversary-midi-pack/
No Rest for the Living: https://www.doomworld.com/vb/thread/119301
Plutonia: https://www.doomworld.com/idgames/music/plutmidi

**Comment by Owlet7** [comment]
Some people have already done something to this effect, check out #29 and #31.

But as the readme states:
> WadFusion is not a general-purpose tool for merging DOOM WADs; it is for *merging official content* only—it was created out of a desire for a "complete" version of retail DOOM and DOOM II. Please do not ask if WadFusion will support any specific WAD. **This includes any content from the 5th generation console ports.** If you want to add your own content to a custom IPK3, either modify WadFusion's code yourself, or simply edit the IPK3 that WadFusion generates. Please do not ask us for support when doing either, try consulting the [ZDoom Wiki](https://zdoom.org/wiki/Main_Page) instead.
