### ISSUE TITLE
texture replacement problems

### ISSUE THREAD

**Issue by BouncyTEM** [Owlet7/wadfusion#4]
STEP1 gives issues in doom 1 because of a flat with the same name. Shown here.
additionally bigdoor7 doesn't look right, either.
![Screenshot_Doom_20240912_102019](https://github.com/user-attachments/assets/f103c098-6cc0-400c-ab30-6f390e91d31b)

**Comment by Owlet7** [comment]
Flats should now be excluded from texture replacement. Is BIGDOOR7 fine now?

**Comment by BouncyTEM** [comment]
it looks correct in doom 1 now, fantastic!

overall I think most of the problems I spotted were fixed, however there is still one remaining

most visibly evident with the test map for Legacy of Rust - the doors are being overwritten by bigdoor7. I included comparison shots here.

also with the map renaming into lr_mapxx the wf_handler needs updating to account for that, it's still looking for id I think based on what I saw

![Screenshot_Doom_20240912_234731](https://github.com/user-attachments/assets/18c83a93-ddb4-424e-99c2-5ba07cbea3db)
![Screenshot_Doom_20240912_234806](https://github.com/user-attachments/assets/46f6740b-ffca-4ada-951b-f1976b9c0f3a)

**Comment by Owlet7** [comment]
Good catch! That's a new texture in id1.wad that shares its name with what I renamed the Doom 1 variant of BIGDOOR7 to.
![Screenshot_Doom_20240913_155119](https://github.com/user-attachments/assets/b1076cbf-1548-47f3-8446-630bf3407601)
I don't think there are any other texture conflicts like that. Were there any other issues related to the BIGDOOR7 replacement?

**Comment by BouncyTEM** [comment]
Not that I am aware of at the present time - if I spot anything else I will let you know!
