### ISSUE TITLE
Add the ID Anthology fixes for final doom.

### ISSUE THREAD

**Issue by justtoask** [Owlet7/wadfusion#40]
[Here's the list.](https://doomwiki.org/wiki/Versions_of_Doom_and_Doom_II#Final_Doom.2C_id_Anthology_version) It'd be nice if wadfusion included the fixes for any version of the wad included. I have the archive of all the different/unique files from those wads if you want.

**Comment by Owlet7** [comment]
Which ones aren't already fixed by GZDoom?

**Comment by justtoask** [comment]
Well I heard the TNT yellow key patch was fixed by, however I'm not sure about Plutonia.

**Comment by Owlet7** [comment]
Implemented the fixes to TNT MAP10, and Plutonia MAP12 and MAP23. The TNT MAP31 key bug is already fixed in GZDoom. The other fixes are on the engine level, so they're not relevant.
