### ISSUE TITLE
Master Levels missing "NoJump" and "NoCrouch" variable after compiling

### ISSUE THREAD

**Issue by Trimint123** [Owlet7/wadfusion#5]
Title is self explanatory.
![image](https://github.com/user-attachments/assets/2e604de8-fd13-4d70-80bc-04ffe22b8d67)
![image](https://github.com/user-attachments/assets/7043bd9e-ec24-403b-8503-21dab097bb11)

**Comment by Owlet7** [comment]
I just published an update to the script an hour ago that completely removed MAPINFO generation for the Master Levels, it now uses a pre-authored one instead, so this issue is no longer relevant.
