### ISSUE TITLE
Legacy of Rust weapon options

### ISSUE THREAD

**Issue by BouncyTEM** [Owlet7/wadfusion#7]
Not a priority or anything, just a thought of something i'd like to see - right now there's the option of having the incinerator and calamity blade in LoR or not, but, what about the reverse? what if I want to use those in doom 2, for instance? It should be relatively easy to have the cvar expanded for a use case like that, right?

or possibly a both option where it's like a 50/50 chance of either showing up. that'd be fun too.

**Comment by Trimint123** [comment]
I was consider the same idea when I saw the possibility, such as replacing non-boss Cyberdemon and Spiderdemon with Tyrant and Mindweaver respectively (obviously not every Cyberdemon and Spiderdemon, of course) and maybe make Vassago appear as a boss in Episode 1 of Doom 1.

But at that point, I would probably be asking for Doom 2 assets in Doom 1 to be reminiscing to PSX Doom.

**Comment by Owlet7** [comment]
This is beyond the scope of the project. That option isn't intended to offer gameplay variety, but to ensure compatibility.

With the latest commit, the idkfa cheat should now also give the Incinerator and Heatwave in any campaign.

**Comment by Owlet7** [comment]
I gave this some more consideration, and realised that replacing the weapons on all maps should be a compatibility option as well, in case of potential mods that require id1-weap.wad, so I implemented that option. Changing the issue from "not planned" to "completed".
