### ISSUE TITLE
Romero Levels (e1m4b/e1m8b)

### ISSUE THREAD

**Issue by domyoji81** [Owlet7/wadfusion#8]
Would adding the Romero levels (e1m4b/e1m8b) be beyond the scope of the project? They're something of a grey area I suppose, but I would still consider them "official" seeing as they were made by Romero to replace those specific maps. JP made an additional pk3 for loading them with Wadsmoosh some time ago as well. In my own personal build I put the wads in the map folder and added them into the mapinfo.txt to follow right after e1m4/e1m8 and then exit to e1m5/endgame1 and added their map names to language.csv, so it's still just the one pk3. Could add e1m4b.wad/e1m8b.wad detection to the script to dump them automatically in the maps folder, and then add a toggle in the WadFusion options to enable or disable them, either as a replacement for the base levels or to run in sequence with them. Sort of like how it is with the xbox levels, but changing mapinfo instead of linedefs.

**Comment by Owlet7** [comment]
Sorry, but on the grey area of official or not, these two are more on the side of not.

If one wishes to have these maps replace the official ones, it's as simple as loading them normally as a PWAD. Putting them in the regular level order makes no sense to me, but of course you're free to keep using a modified MAPINFO that achieves this.

The map order in MAPINFO can't be changed with a toggle in the options, but the level transition can probably be scripted to work like that. If you submit a pull request for this feature, it can be considered, but for now, I'm closing it as not planned.

**Comment by Owlet7** [comment]
Implemented in #19.
